
paths:
  /clients/{clientId}/therapists/{therapistId}/access:
    post:
      summary: Grant access to client's journal for a therapist
      operationId: grantAccessToTherapist
      parameters:
        - in: path
          name: clientId
          required: true
          schema:
            type: string
        - in: path
          name: therapistId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Access granted to therapist's journal
        '404':
          description: Client or Therapist not found

  /clients/{clientId}/therapists/{therapistId}/access:
    delete:
      summary: Remove access to client's journal for a therapist
      operationId: removeAccessToTherapist
      parameters:
        - in: path
          name: clientId
          required: true
          schema:
            type: string
        - in: path
          name: therapistId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Access removed from therapist's journal
        '404':
          description: Client or Therapist not found
